### ISSUE TITLE
TypeError: 'Commit' object is not subscriptable

### ISSUE THREAD

**Issue by j6k4m8** [test-room-7/action-update-file#1]
When writing a simple text file and running this action, I encounter the following:

```
Traceback (most recent call last):
  File "/entrypoint.py", line 106, in <module>
    sys.exit(main())
  File "/entrypoint.py", line 97, in main
    commit_sha = pushed_change['commit'][:SHORT_SHA_LEN]
TypeError: 'Commit' object is not subscriptable
```

Is there some way around this?

**Comment by alexesprit** [comment]
Hi! I pushed a commit (cd311d28a8870b6f504d9f2061bb0abeab70beef) which should fix the issue. Could you check it and tell if the issue is fixed for you?

**Comment by j6k4m8** [comment]
Confirmed! Thank you!
