### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by jnichols35** [test-room-7/action-update-file#18]
While running an action I get the following error/warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: test-room-7/action-update-file

**Comment by alexesprit** [comment]
Resolved in #19.
