### ISSUE TITLE
set-output deprecated

### ISSUE THREAD

**Issue by shawaj** [test-room-7/action-update-file#20]
The action gives warnings in relation to deprecated set-output. 

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Relates to #17 and #18

However according to the above link the action/core package needs to be bumped to v1.10.0 or higher

**Comment by alexesprit** [comment]
Fixed in v1.8.0

**Comment by shawaj** [comment]
Awesome 😎
