### ISSUE TITLE
binary files are committed incorrectly

### ISSUE THREAD

**Issue by dukess** [test-room-7/action-update-file#5]
Hello! 
I tried using the script and I liked the result, except that when copying binary files (gzipped javascript), they break.
Is it possible to fix this?
Workflow file: https://github.com/dukess/bsb_lan/blob/master/.github/workflows/localization.yaml

**Comment by alexesprit** [comment]
Hi! Thanks for reporting the issue.

Not sure why it happens; perhaps binary files should be updated using a different way. I'll investigate this issue.

**Comment by dukess** [comment]
If it helps:
I tried add .gitattributes file to root directory with 
`*.js.gz binary`
but nothing changes (or i did something wrong)

**Comment by alexesprit** [comment]
Looks like I figured out why the actions corrupts binary files.

I made an attempt to fix this in [create-blob](https://github.com/test-room-7/action-update-file/tree/create-blob) branch, though I can't test changes now - GitHub Actions [are down](https://github.com/test-room-7/action-update-file/tree/create-blob). I will try to test changes later, and we'll see if this fix works or not.

**Comment by dukess** [comment]
Thank you!
Now binary files committing correctly.

**Comment by dukess** [comment]
Вопрос уже философский, на будущее: насколько велики шансы, что этот скрипт будет в будщем удалён, имеет ли смысл утащить его к себе?

**Comment by alexesprit** [comment]
Не понял, про какой скрипт идёт речь?

**Comment by dukess** [comment]
Собственно, про этот: test-room-7/action-update-file
Пожалуй, неудачно назвал скриптом.

**Comment by alexesprit** [comment]
Ааа, ты про экшен. Нет, я не буду его удалять, зачем? Я сам им пользуюсь в своих проектах. Сегодня ещё протестирую и залью обновление бинарных файлов в основную ветку.

**Comment by dukess** [comment]
Ок. Ещё раз спасибо!
