### ISSUE TITLE
Always get 'No files to update'

### ISSUE THREAD

**Issue by lswlover2579** [test-room-7/action-update-file#6]
I just copy your update code and always get this

**Comment by lswlover2579** [comment]
**my yml**:
`        run: python3 VideoParse.py

      - name: 'Update resources'
        uses: test-room-7/action-update-file@v1
        with:
          # Include all JS files from the `dist` directory
          file-path: Series.m3u
          commit-msg: Update resources
          github-token: ${{ secrets.PAT }}`

**action info**:
`Run test-room-7/action-update-file@v1
  with:
    file-path: Series.m3u
    commit-msg: Update resources
    github-token: ***
    allow-dot: false
    allow-removing: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.7/x64
No files to update`

**Comment by alexesprit** [comment]
@lswlover2579 make sure your file is updated by other scripts and/or actions.

**Comment by lswlover2579** [comment]
I just need your action to achive update task
But now I use another action over it lol
