### ISSUE TITLE
Error: Server Error

### ISSUE THREAD

**Issue by ghost** [test-room-7/action-update-file#9]
https://github.com/complexorganizations/content-blocker/runs/2895502977?check_suite_focus=true

Where did i go wrong?

**Comment by ghost** [comment]
Anyone have any idea on how to fix this?

**Comment by ghost** [comment]
https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token

Guys use this instead.

**Comment by davidcalhoun** [comment]
I've been getting this error happening about 50% of runs, super annoying.  Thanks for the info about using `actions/checkout` instead to push!
